[package]
name = "rust-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
load-config-derive = { path = "../load-config-derive" }

clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_yaml = "0.9.27"
eyre = "0.6.8"
